### ISSUE TITLE
how can i update the offsets i cant find smt named offsets

### ISSUE THREAD

**Issue by justchillingrnyk** [nezu-cc/BakaWare4#4]
self explained

**Comment by dumbasPL** [comment]
You'll need **WAY** more than just offsets. The game has changed a lot since then, so unless you know what you're doing and can reverse all the new stuff you won't get far just updating offsets and signatures

> i cant find smt named offsets

Maybe because I find them myself so the names I give them are my own and might not align with what other people called them, also many sigs here are unique and you won't find them on UC or other forums.

**Comment by justchillingrnyk** [comment]
im too retarded to do all that
